service: MoonMail-v2-job-scheduler

plugins:
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs6.10
  profile: ${self:custom.config.PROFILE}
  region: ${self:custom.config.REGION}
  timeout: 300
  environment:
    REGION: ${self:custom.config.REGION}
    SCHEDULE_JOBS_TABLE: 'scheduledjobssrv-scheduled-jobs'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

package:
  individually: true

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  resourcesPrefix: ${self:service}-${self:custom.currentStage}
  config: ${file(./config.${self:custom.currentStage}.json)}

functions:
  scheduleJob:
    handler: handler.scheduleJob
  updateJobStatus:
    handler: handler.updateJobStatus
  findJobsToBeTriggered:
    handler: handler.findJobsToBeTriggered
    events:
      - schedule: rate(2 minutes)

resources:
  Resources:
    ScheduleJobsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.SCHEDULE_JOBS_TABLE}
    
